# Generated by Django 5.2.6 on 2025-09-28 16:50

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('file', models.ImageField(help_text='Upload image file', upload_to='images/%Y/%m/', verbose_name='Image File')),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated or custom thumbnail', null=True, upload_to='thumbnails/%Y/%m/', verbose_name='Thumbnail')),
                ('image_type', models.CharField(choices=[('cover', 'Cover/Featured Image'), ('gallery', 'Gallery Image'), ('logo', 'Logo'), ('icon', 'Icon'), ('screenshot', 'Screenshot'), ('certificate', 'Certificate'), ('team', 'Team Photo'), ('document', 'Document/PDF Preview'), ('other', 'Other')], default='gallery', max_length=20, verbose_name='Image Type')),
                ('order', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Display Order')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured image for the related object', verbose_name='Is Featured?')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=50, verbose_name='MIME Type')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['order', '-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ImageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=255, verbose_name='Alt Text')),
                ('caption', models.TextField(blank=True, verbose_name='Caption')),
                ('credits', models.CharField(blank=True, max_length=200, verbose_name='Credits/Attribution')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.image')),
            ],
            options={
                'verbose_name': 'Image Translation',
                'db_table': 'core_image_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['content_type', 'object_id'], name='core_image_content_3bdd6a_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['image_type'], name='core_image_image_t_2a8ff9_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['is_featured'], name='core_image_is_feat_de8a21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imagetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
