# Generated by Django 5.2.6 on 2025-10-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="category",
        ),
        migrations.AlterUniqueTogether(
            name="categorytranslation",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="CategoryTranslation",
        ),
    ]
