# Generated by Django 5.2.6 on 2025-11-21 17:59

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image_imagetranslation_and_more'),
        ('portfolio', '0002_remove_project_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date', '-end_date'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date', '-end_date'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('achievement_type', models.CharField(choices=[('award', 'Award/Prize'), ('recognition', 'Recognition'), ('competition', 'Competition'), ('publication', 'Publication'), ('patent', 'Patent'), ('other', 'Other')], default='other', max_length=20, verbose_name='Type')),
                ('date', models.DateField(verbose_name='Date')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Related URL')),
                ('position', models.CharField(blank=True, help_text="e.g., '1st Place', 'Top 10', 'Finalist'", max_length=50, verbose_name='Position/Ranking')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='portfolio.project', verbose_name='Related Project')),
                ('skills', models.ManyToManyField(blank=True, related_name='achievements', to='portfolio.skill', verbose_name='Related Skills')),
                ('tags', models.ManyToManyField(blank=True, related_name='achievements', to='core.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['-featured', '-date', 'sort_order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('credential_id', models.CharField(blank=True, max_length=120, verbose_name='Credential ID')),
                ('credential_url', models.URLField(blank=True, help_text='URL for verification', null=True, verbose_name='Credential URL')),
                ('featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('skills', models.ManyToManyField(blank=True, related_name='certificates', to='portfolio.skill', verbose_name='Related Skills')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-featured', '-issue_date', 'sort_order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AchievementTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Slug')),
                ('issuer', models.CharField(max_length=160, verbose_name='Issuer/Organization')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='portfolio.achievement')),
            ],
            options={
                'verbose_name': 'Achievement Translation',
                'db_table': 'portfolio_achievement_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CertificateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Certificate Name')),
                ('slug', models.SlugField(blank=True, max_length=220, verbose_name='Slug')),
                ('issuer', models.CharField(max_length=160, verbose_name='Issuer/Institution')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='portfolio.certificate')),
            ],
            options={
                'verbose_name': 'Certificate Translation',
                'db_table': 'portfolio_certificate_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
