# Generated by Django 5.2.6 on 2025-10-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contentblock',
            name='uq_contentblock_page_key',
        ),
        migrations.RemoveIndex(
            model_name='contentblock',
            name='content_con_page_be83e6_idx',
        ),
        migrations.RenameField(
            model_name='contentblock',
            old_name='page',
            new_name='page_name',
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['page_name'], name='content_con_page_na_497d28_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.UniqueConstraint(fields=('page_name', 'key'), name='uq_contentblock_page_key'),
        ),
    ]
